config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  devise_for :users,
  path: '',
  controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  },
  path_names: {
    sign_in: 'login',
    password: 'forgot',
    confirmation: 'confirm',
    sign_up: 'sign_up',
    sign_out: 'signout'
  }

  get 'dashboard/show'

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
    validates_presence_of :name

    has_many :jobs, dependent: :destroy
    has_many :users, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :account

  has_rich_text :description
  validates_presence_of :title, :status, :job_type, :location

  enum status: {
    draft: 'draft',
    open: 'open',
    closed: 'closed'
  }

  enum job_type: {
    full_time: 'full_time',
    part_time: 'part_time'
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :account
  accepts_nested_attributes_for :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include CableReady::Broadcaster
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(job_params)
    @job.account = current_user.account
    if @job.save
      render turbo_stream: turbo_stream.prepend(
        'jobs',
        partial: 'job',
        locals: { job: @job }
      )
    else
      render turbo_stream: turbo_stream.replace(
        'job-form',
        partial: 'form',
        locals: { job: @job }
      ), status: :unprocessable_entity
    end
  end

  # GET /jobs/1/edit
  def edit
    html = render_to_string(partial: 'form', locals: { job: @job })
    render operations: cable_car
      .inner_html('#slideover-content', html: html)
      .text_content('#slideover-header', text: 'Update job')
  end

  # POST /jobs or /jobs.json
 

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    if @job.update(job_params)
      html = render_to_string(partial: 'job', locals: { job: @job })
      render operations: cable_car
        .replace(dom_id(@job), html: html)
        .dispatch_event(name: 'submit:success')
    else
      html = render_to_string(partial: 'form', locals: { job: @job })
      render operations: cable_car
        .inner_html('#job-form', html: html), status: :unprocessable_entity
    end
  end
  

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    render turbo_stream: turbo_stream.remove(@job)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :status, :job_type, :location, :account_id)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def new
    build_resource
    resource.build_account
    yield resource if block_given?
    respond_with resource
  end

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      # set status to unprocessable_entity so form errors are rendered
      respond_with resource, status: :unprocessable_entity
    end
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      account_attributes: [:id, :name]
    ])
  end

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super do
      return redirect_to root_path
    end
  #   super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level.to_sym
        when :notice
          'bg-blue-900 border-blue-900'
        when :success
          'bg-green-900 border-green-900'
        when :alert
          'bg-red-900 border-red-900'
        when :error
          'bg-red-900 border-red-900'
        else
          'bg-blue-900 border-blue-900'
        end
      end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/dashboard/show.html.erb
<h1>Dashboard#show</h1>
<p>Probando...</p>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/jobs/_form.html.erb
<%= form_with(
  model: job,
  id: 'job-form',
  html: { class: "space-y-6" },
  data: {
    slideover_target: "form"
  }
) do |form| %>

  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <div class="mt-1">
      <%= form.text_field :title %>
    </div>
  </div>

  <div class="form-group">
    <%= form.rich_text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Job.statuses.map{|key, _value| [key.humanize, key]}, job.status), {}, { class: "mt-1" } %>
  </div>

  <div class="form-group">
    <%= form.label :job_type %>
    <%= form.select :job_type, options_for_select(Job.job_types.map{|key, _value| [key.humanize, key]}, job.job_type), {}, { class: "mt-1" } %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <div class="mt-1">
      <%= form.text_field :location %>
    </div>
  </div>

  <%= form.submit 'Submit', class: 'btn-primary float-right' %>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id(job) %>">
  <div class="flex flex-col md:flex-row items-center px-4 py-4 sm:px-6 justify-between">
    <div class="flex-1">
    <%= link_to job.title,
    edit_job_path(job),
    class: "text-lg text-blue-600 hover:text-blue-700",
    data: {
      action: "click->slideover#open",
      remote: true
    } %>
      <div class="flex space-x-2 text-gray-500 text-sm">
        <div>
          <%= job.location %>
        </div>
        <div>
          <%= job.job_type.humanize %>
        </div>
      </div>
    </div>
    <div class="text-right">
    <%= button_to "Delete job",
  job_path(job),
  method: :delete,
  class: "btn border border-red-200 hover:bg-red-100 text-sm text-red-700",
  data: { confirm: "Are you sure?" } 
%>
    </div>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<div class="flex items-baseline justify-between mb-6">
  <h2 class="mt-6 text-3xl font-extrabold text-gray-700">
    Jobs
  </h2>
  <%= link_to "Post a job",
  new_job_path,
  class: "btn-primary-outline",
  data: {
    action: "click->slideover#open",
    turbo_frame: 'slideover'
  } %>
</div>
<div class="shadow overflow-hidden sm:rounded-md" id="jobs">
  <div class="divide-y divide-gray-200">
    <%= render @jobs %>
  </div>
</div>

app/views/jobs/new.html.erb
<%= turbo_frame_tag "slideover" do %>
  <div class="flex px-6 justify-between items-baseline bg-gray-900">
    <h3 class="text-xl text-white" id="slideover-header">Add a new job posting</h3>
    <button data-action="slideover#close" class="flex items-center justify-center h-12 w-12 rounded-full focus:outline-none focus:bg-gray-600 hover:bg-gray-600" aria-label="Close slideover">
      <%= inline_svg_tag 'close.svg', class: "h-7 w-7 text-white" %>
    </button>
  </div>
  <div class="mt-4 px-4 text-gray-700">
    <div id="slideover-content">
      <%= render "form", job: @job %>
    </div>
  </div>
<% end %>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwiredAts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body data-controller="slideover">
  <div class="flex flex-col h-screen justify-between px-4 md:px-0">
    <%= render "nav/top_nav" %>
    <main class="mb-auto w-full overflow-auto">
      <div class="mx-auto max-w-7xl md:px-6 lg:px-8 py-8">
        <%= yield %>
      </div>
    </main>
    <%= render "shared/footer" %>
    <div id="flash-container">
      <% flash.each do |key, value| %>
        <%= render "shared/flash", level: key, content: value %>
      <% end %>
    </div>
  </div>
  <%= render "shared/slideover" %>
</body>
</html>

app/views/nav/_authenticated.html.erb
<div class="flex items-center w-full space-x-8">
  <%= link_to "Jobs", jobs_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
  <a class="rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" href="#">Applicants</a>
</div>
<div class="flex items-center justify-end px-6 py-4 flex-shrink-0 space-x-8">
  <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
</div>

app/views/nav/_top_nav.html.erb
<nav class="bg-gray-100 shadow">
  <div class="container mx-auto flex text-gray-700 max-w-screen-2xl">
    <div class="flex flex-shrink-0 items-center px-6 py-4">
      <%= link_to "Hotwired ATS", root_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
    </div>
    <% if user_signed_in? %>
      <%= render "nav/authenticated" %>
    <% else %>
      <%= render "nav/unauthenticated" %>
    <% end %>
  </div>
</nav>

app/views/nav/_unauthenticated.html.erb
<div class="flex items-center ml-12 w-full"></div>
<div class="flex items-center justify-end px-6 py-4 flex-shrink-0 space-x-8">
  <%= link_to "Sign In", new_user_session_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
</div>

app/views/shared/_flash.html.erb
<div class="fixed inset-x-0 -bottom-32 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-50 pointer-events-none">
  <div data-controller="alert" class="max-w-sm w-full h-24 shadow-lg rounded px-4 py-3 rounded relative border-l-4 text-white pointer-events-auto <%= flash_class(level) %>">
    <div class="p-2">
      <div class="flex items-start">
        <div class="ml-3 w-0 flex-1 pt-0.5">
          <p class="text-sm leading-5">
            <%= content %>
          </p>
        </div>
        <div class="ml-4 flex-shrink-0 flex">
          <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
            <%= inline_svg_tag 'close.svg', class: 'h-4 w-4 inline-block' %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-gray-100 border-t border-gray-200">
  <div class="max-w-screen-2xl mx-auto py-6 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
    <div class="mt-8 md:mt-0">
      <p class="text-center text-gray-700 text-sm">
        &copy; <%= Date.current.year %> Hotwired ATS
      </p>
    </div>
    <div class="flex justify-center space-x-6">
      <%= link_to "Terms of Service", "#", class: "text-gray-700 hover:text-gray-900 text-xs" %>
      <%= link_to "Privacy Policy", "#", class: "text-gray-700 hover:text-gray-900 text-xs" %>
    </div>
  </div>
</footer>

app/views/shared/_slideover.html.erb
<%= turbo_frame_tag(
  "slideover",
  data: {
    slideover_target: "slideover",
    action: "turbo:submit-end->slideover#handleResponse"
  },
  class: "h-screen overflow-y-scroll fixed -right-full lg:-right-1/3 top-0 flex-1 flex flex-col w-full lg:w-1/3 bg-gray-100 transition-all duration-500 z-50"
) %>